export enum DocumentType {
  NOTA_FISCAL = 'NOTA_FISCAL',
  CONTRATO_DE_TRABALHO = 'CONTRATO_DE_TRABALHO',
  HOLERITE_DE_PAGAMENTO = 'HOLERITE_DE_PAGAMENTO',
  RECIBO_DE_PAGAMENTO = 'RECIBO_DE_PAGAMENTO',
  ATESTADO_MEDICO = 'ATESTADO_MEDICO',
  FOLHA_DE_PONTO = 'FOLHA_DE_PONTO',
  CERTIFICADO = 'CERTIFICADO',
  CONTRATO_PRESTACAO_DE_SERVICO = 'CONTRATO_PRESTACAO_DE_SERVICO',
}
